# Copyright 2020 Jack Grigg
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

### Localization for strings in the rage CLI tool

## CLI flags

-flag-armor = -a/--armor
-flag-decrypt = -d/--decrypt
-flag-identity = -i/--identity
-flag-recipient = -r/--recipient
-flag-passphrase = -p/--passphrase
-flag-max-work-factor = --max-work-factor
-flag-unstable = --features unstable

## Encryption messages

autogenerated-passphrase = Using an autogenerated passphrase:
type-passphrase = Type passphrase
prompt-passphrase = Passphrase

## General errors

err-passphrase-timed-out = Timed out waiting for passphrase input.

err-ux-A = Did rage not do what you expected? Could an error be more useful?
err-ux-B = Tell us
# Put (len(A) - len(B) - 32) spaces here.
err-ux-C = {"                          "}

## Encryption errors

err-enc-broken-stdout = Could not write to stdout: {$err}
rec-enc-broken-stdout = Are you piping to a program that isn't reading from stdin?

err-enc-broken-file = Could not write to file: {$err}

err-enc-identity = {-flag-identity} can't be used in encryption mode.
rec-enc-identity = Did you forget to specify {-flag-decrypt}?

err-enc-invalid-recipient = Invalid recipient '{$recipient}'

err-enc-missing-recipients = Missing recipients.
rec-enc-missing-recipients = Did you forget to specify {-flag-recipient}?

err-enc-mixed-recipient-passphrase = {-flag-recipient} can't be used with {-flag-passphrase}
err-enc-passphrase-without-file = File to encrypt must be passed as an argument when using {-flag-passphrase}
err-enc-unknown-alias = Unknown {$alias}

## Decryption errors

rec-dec-excessive-work = To decrypt, retry with {-flag-max-work-factor} {$wf}

err-dec-armor-flag = {-flag-armor} can't be used with {-flag-decrypt}.
rec-dec-armor-flag = Note that armored files are detected automatically.

err-dec-identity-not-found = Identity file not found: {$filename}

err-dec-missing-identities = Missing identities.
rec-dec-missing-identities-1 = Did you forget to specify {-flag-identity}?
rec-dec-missing-identities-2 = You can also store default identities in this file:

err-dec-passphrase-flag = {-flag-passphrase} can't be used with {-flag-decrypt}.
rec-dec-passphrase-flag = Note that passphrase-encrypted files are detected automatically.

err-dec-passphrase-without-file-win =
    This file requires a passphrase, and on Windows the
    file to decrypt must be passed as a positional argument
    when decrypting with a passphrase.

err-dec-recipient-flag = {-flag-recipient} can't be used with {-flag-decrypt}.
rec-dec-recipient-flag = Did you mean to use {-flag-identity} to specify a private key?

## Unstable features

unstable-aliases = Aliases are unstable.
unstable-github = GitHub lookups are unstable, ignoring recipient.
test-unstable = To test this, build rage with {-flag-unstable}.
